### PR TITLE
Replace S3 host with Cloudfront distibution, if provided

### LINKED ISSUE #17: Substitute screenshot URL host with CloudFront prefix, if given
We need to add an environment variable, optionally set with a Cloudfront  distribution, which is used to replace the S3 hostname in a screenshot URL

### PR DESCRIPTION
**Pull request by cadecairos**
fixes #17 

@toolness Did I miss anything? I'm not sure how the tests work here either, can you advise?

@simonwex I'm fairly sure I did this right, s/{S3 hostname}/{Cloudfront distribution} right?

### CODE REVIEW

**Comment by toolness** [comment]
I'm confused, does this actually need to be done? I mentioned in https://github.com/mozilla/api.webmaker.org/issues/64#issuecomment-108585888:

> So I just realized that one of the features the screenshot service already supports is an optional [`S3_WEBSITE` environment variable](https://github.com/mozilla/webmaker-screenshot#optional-environment-variables):

> > If your S3 bucket is hosted at a custom domain, you can optionally set `S3_WEBSITE` to its origin followed by a `/`, e.g. `http://my-webmaker-screenshots.com/`.

> This was originally intended to work with S3's virtual hosting capabilities, but based on the little I know of how CloudFront works, I *think* it would work with CloudFront too. (Really `S3_WEBSITE` is just what's prepended to the S3 key name to provide the absolute URL to the resource.)  Any idea, @simonwex?

I don't think @simonwex responded yet though.

**Comment by toolness** [comment]
I am pretty sure we can just use `S3_WEBSITE` for this. `S3_WEBSITE` isn't even limited to pointing the root of a website, e.g. it could be `https://my-cloudfront-thing.com/myfunkydirectory/`.

**Comment by cadecairos** [comment]
Yeah, that might be all we need!

Does blitline's response include that url?

**Comment by toolness** [comment]
I don't think blitline's response includes that URL, but we're not forwarding blitline's response--we're telling blitline exactly what bucket and key to put the screenshot in, and then we're giving the client back a URL that we know points to the same place.

So as long as cloudfront instantly pokes at the same bucket+key that we told blitline to save the screenshot in, I think we should be good (but I also don't know enough about cloudfront to know if my assumption about it is correct).

**Comment by cadecairos** [comment]
Based on what I read in the cloudfront docs, that does appear to be accurate.

**Comment by toolness** [comment]
Hooray!!!!

**Comment by cadecairos** [comment]
Once I set up staging with our Moz blitline account, a new s3 bucket and set up cloudfront, I'll confirm that we can use S3_WEBSITE and then close this, and #18

**Pull request closed without merging**
